### ISSUE TITLE
Waitscreen

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#11]
![screen shot 2017-09-20 at 7 23 39 pm](https://user-images.githubusercontent.com/6261302/30655685-63ad80f2-9e3a-11e7-8c72-c942f96bd03c.png)

**Comment by DaQuirm** [comment]
I'm not sure if that's the right place to discuss this, but I would suggest importing the [wait screen concept](https://github.com/21-23/_qd-ui/issues/74) from _QD (with a random CSS selector replacing lodash API).

**Comment by R1ZZU** [comment]
Closed by #38
