### ISSUE TITLE
Scoreboard

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#13]
<img width="450" alt="screen shot 2017-09-20 at 7 23 47 pm" src="https://user-images.githubusercontent.com/6261302/30656090-8e5d96ba-9e3b-11e7-96e3-8a8cf0b27bc3.png">
<img width="442" alt="screen shot 2017-09-20 at 7 23 54 pm" src="https://user-images.githubusercontent.com/6261302/30656106-9ab7cb1a-9e3b-11e7-87e2-85550a4cd630.png">

**Comment by DaQuirm** [comment]
That's solution time, right? It should be displayed as `xx.yy` or `xx.yyy`, seconds, because of "LvivJS Incident".

**Comment by andrei-yanovich** [comment]
@R1ZZU do we have position # for players?

**Comment by R1ZZU** [comment]
@andrei-yanovich we didn't have in initial implementation, but this sounds like a good idea! 👍

**Comment by DaQuirm** [comment]
@R1ZZU @andrei-yanovich Player places/positions are numbered in _qd

**Comment by DaQuirm** [comment]
\* in the score

**Comment by R1ZZU** [comment]
Closed by #29
