### ISSUE TITLE
Connection lost screen

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#14]
![screen shot 2017-09-20 at 7 44 35 pm](https://user-images.githubusercontent.com/6261302/30656272-33684b46-9e3c-11e7-9710-a03f56291525.png)

**Comment by kirilknysh** [comment]
do we need it? With phoenix - no need to press button to re-connect. I'd vote for simple input disabling when phoenix is disconnected.

**Comment by R1ZZU** [comment]
Maybe we can get rid of button itself, but IMO we need dedicated screen indicating connectivity issues

**Comment by andrei-yanovich** [comment]
What's the decision, do we need a separate screen and/or the button

**Comment by R1ZZU** [comment]
I'd handle connection lost with grayscale filter on all elements (ui will fade to gray, but no visible controls needed)
