### ISSUE TITLE
Pearl thread

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#3]
<img width="1236" alt="screen shot 2017-09-20 at 7 20 43 pm" src="https://user-images.githubusercontent.com/6261302/30655456-9b5c4b1a-9e39-11e7-9ec5-40d1123151d1.png">

**Comment by kirilknysh** [comment]
Should be click-able on Game Master and "read-only" on Game. Potentially, should be clickable on Game for watching history (past rounds clickable, future - read-only)

**Comment by KantinDmitry** [comment]
https://github.com/21-23/cssqd-ui/pull/40
