### ISSUE TITLE
Countdown

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#4]
<img width="170" alt="screen shot 2017-09-20 at 7 20 50 pm" src="https://user-images.githubusercontent.com/6261302/30655479-ad8976f0-9e39-11e7-8f88-0d1ac0f4e6e8.png">

**Comment by kirilknysh** [comment]
Minimal incoming params:
- size (different size on GM and G)
- color (during round - yellow, if success - green)
