### ISSUE TITLE
Markup renderer

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#5]
<img width="1228" alt="screen shot 2017-09-20 at 7 23 29 pm" src="https://user-images.githubusercontent.com/6261302/30655499-bdf5fb58-9e39-11e7-970a-5c005d272118.png">

**Comment by kirilknysh** [comment]
Do we want the "whole-line-highlight"? Maybe "the original" dots?

**Comment by R1ZZU** [comment]
I'd say "highlight mode" should be configurable (HOC ideally), so we can experiment with several approaches

**Comment by DaQuirm** [comment]
I'd vote for the original solid/stroke circles
