### ISSUE TITLE
Pearl thread default click handler

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#56]
![pasted_image_at_2017_11_27_01_02_am](https://user-images.githubusercontent.com/6261302/33244915-f00a5218-d310-11e7-81d8-28bdacbbde5d.png)

**Comment by kirilknysh** [comment]
On game.html, the issue is that:

1. Cursor is “pointer”
2. Click handler has no effect, but throws an error (see screenshot)
