### ISSUE TITLE
Banned characters

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#6]
<img width="184" alt="screen shot 2017-09-20 at 7 21 08 pm" src="https://user-images.githubusercontent.com/6261302/30655560-f1179e88-9e39-11e7-8776-f2405ddf51d2.png">

**Comment by kirilknysh** [comment]
Should be highlightable

**Comment by R1ZZU** [comment]
<img width="229" alt="screen shot 2017-09-20 at 7 56 03 pm" src="https://user-images.githubusercontent.com/6261302/30656755-c715f52c-9e3d-11e7-9cff-7862cc0fa079.png">
