### ISSUE TITLE
Game flow control

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#8]
<img width="180" alt="screen shot 2017-09-20 at 7 21 38 pm" src="https://user-images.githubusercontent.com/6261302/30655595-20b28e46-9e3a-11e7-8c92-1d93495bbb2d.png">

**Comment by kirilknysh** [comment]
Log out button in header is the same but with with icon in the right.

**Comment by andrei-yanovich** [comment]
what states does this button have?

**Comment by R1ZZU** [comment]
<img width="170" alt="screen shot 2017-11-05 at 10 29 02 pm" src="https://user-images.githubusercontent.com/6261302/32418331-6cf26308-c270-11e7-86b1-a746e5f0139c.png">
<img width="177" alt="screen shot 2017-11-05 at 10 29 10 pm" src="https://user-images.githubusercontent.com/6261302/32418332-6d1624c8-c270-11e7-8afd-978e559c8b77.png">
