### ISSUE TITLE
Round title

### ISSUE THREAD

**Issue by R1ZZU** [21-23/cssqd-ui#9]
<img width="214" alt="screen shot 2017-09-20 at 7 21 46 pm" src="https://user-images.githubusercontent.com/6261302/30655620-3af34f8e-9e3a-11e7-9df0-14d8c1c16717.png">

**Comment by DaQuirm** [comment]
Let's also agree on terminology across-projects.
I and @kirilknysh spent quite some time discussing how various "business" entities should be named for _QD. 
See [this](https://github.com/21-23/_qd/wiki/QDP) for the Glossary (suggestions are always welcome) 😸

**Comment by R1ZZU** [comment]
Closed by #33
